var express = require('express');
var r = require('rethinkdb');
var router = express.Router();

router.get("/api/project/:project", function(req, res) {
    r.connect({host: '159.203.246.210', port: 28015}, function(err, conn){
        if(err) {
            res.status = 500;
            return res.json({success: false, reason: 'Database Connection Error'});
        }

        r.db('ProjectBoard').table('projects').get(req.params.project).run(conn, function(err, result){
            if(err) {
                res.status = 500;
                return res.json({success: false, reason: 'Database Transaction Error'});
            }
            if(!result) {
                res.status = 400;
                return res.json({success: false, reason: 'No Such Project'})
            }
            res.json(result);
        })
    });
});

router.post('/api/project/', function(req, res){
    if(!req.query.name) return res.json({success: false, reason: "'name' is a required field"});
    if(!req.query.author) return res.json({success: false, reason: "'author' is a required field"});

    r.connect({host: '159.203.246.210', port: 28015}, function(err, conn){
        if(err) {
            res.status = 500;
            return res.json({success: false, reason: 'Database Connection Error'});
        }

        r.db('ProjectBoard').table('projects').insert({
            name: req.query.name,
            submitter: req.query.author,
            status: 'proposed',
            approved: false,
            lead: null
        }).run(conn); //TODO return rethinkDB autogenerated UID to user in JSON script
        res.json({success: true, requestedName: req.query.name});
    });
});


module.exports = router;